services:
  redis:
    image: redis:alpine
    container_name: cartservice-redis
    ports:
      - "6379:6379"

  cartservice:
    image: us-central1-docker.pkg.dev/google-samples/microservices-demo/cartservice:v0.10.5
    container_name: cartservice-verify
    depends_on:
      - redis
    environment:
      REDIS_ADDR: redis:6379
      ASPNETCORE_HTTP_PORTS: "7070"
    ports:
      - "7070:7070"